version: 1
groups:
  - annotation: ckanext-relationship
    options:
      - key: ckanext.relationship.views_without_relationships_in_package_show
        type: list
        default: search read
        description: |
          Adding relationships to the package show result can be time-consuming and
          may decrease the performance of pages where this action is called multiple
          times, such as the search page. Therefore, by default, relationships are
          hidden from the package show for both the search page and the package read
          page. To include relationships in the package_show action, you must add the
          flag with_relationships=True to the data_dict.

      - key: ckanext.relationship.show_relationship_graph_on_read
        type: bool
        default: true
        description: |
          Controls whether the optional relationship graph section is added
          automatically to dataset read pages when the relationship_graph plugin
          is enabled. Manual use of the graph snippet in custom templates is not
          affected.

      - key: ckanext.relationship.async_package_index_rebuild
        type: bool
        default: false
        description: |
            If true, when a relationship is created, updated or deleted, the related
            packages will be re-indexed in the background using a task queue. This can
            help improve solve timeouts and performance issues on sites with a large
            number of relationships. If false, the related packages will be re-indexed
            immediately.

      - key: ckanext.relationship.redis_queue_name
        type: base
        default: "default"
        description: |
            The name of the Redis queue to use for background tasks.
